# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stratt < Formula
  desc "A polyglot task runner that replaces Makefiles, manages release versions, and handles Kustomize image bumps."
  homepage "https://stratt.sh"
  version "0.11.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stratt-sh/stratt/releases/download/v0.11.0/stratt_0.11.0_darwin_amd64.tar.gz"
      sha256 "f5679351e9594aee821edd5753a87f451e7682a6b2640c9d1732dd32eeb319f2"

      define_method(:install) do
        bin.install "stratt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stratt-sh/stratt/releases/download/v0.11.0/stratt_0.11.0_darwin_arm64.tar.gz"
      sha256 "af5ddd75c7dd74b5c12fd34e20c5f8074fd0d2beb81b43de6e3c3a25f416a9f1"

      define_method(:install) do
        bin.install "stratt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stratt-sh/stratt/releases/download/v0.11.0/stratt_0.11.0_linux_amd64.tar.gz"
      sha256 "40b41bb740bd7fa022242937fed5aa64c2f9f6a4096fad74f9c0ac78ebdd1bf2"
      define_method(:install) do
        bin.install "stratt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stratt-sh/stratt/releases/download/v0.11.0/stratt_0.11.0_linux_arm64.tar.gz"
      sha256 "42408f02e39b6c9965d54a7d35edf5594992711f9089a0a3cbb8bc25d78c046d"
      define_method(:install) do
        bin.install "stratt"
      end
    end
  end

  test do
    system "#{bin}/stratt version"
  end
end
