# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stratt < Formula
  desc "A polyglot task runner that replaces Makefiles, manages release versions, and handles Kustomize image bumps."
  homepage "https://stratt.sh"
  version "0.12.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stratt-sh/stratt/releases/download/v0.12.0/stratt_0.12.0_darwin_amd64.tar.gz"
      sha256 "3420f05d1aa338e6f6607d1577decc224cb4420bf5d42382fa5a4f295e2e4e5c"

      define_method(:install) do
        bin.install "stratt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stratt-sh/stratt/releases/download/v0.12.0/stratt_0.12.0_darwin_arm64.tar.gz"
      sha256 "871497219dac9bbf5accc54a81e4eb892ac6fe87aeacf080867ac4b1d51248aa"

      define_method(:install) do
        bin.install "stratt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stratt-sh/stratt/releases/download/v0.12.0/stratt_0.12.0_linux_amd64.tar.gz"
      sha256 "8d7394d6ef2aa98b378309818e02295d4350f82cff81544b6608c8328c05a491"
      define_method(:install) do
        bin.install "stratt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stratt-sh/stratt/releases/download/v0.12.0/stratt_0.12.0_linux_arm64.tar.gz"
      sha256 "0289787ccdb7982ea97609ffdc83c9048359a8c77e8cb9a0cd5ad626d5fee592"
      define_method(:install) do
        bin.install "stratt"
      end
    end
  end

  test do
    system "#{bin}/stratt version"
  end
end
