# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stratt < Formula
  desc "A polyglot task runner that replaces Makefiles, manages release versions, and handles Kustomize image bumps."
  homepage "https://stratt.sh"
  version "0.13.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stratt-sh/stratt/releases/download/v0.13.0/stratt_0.13.0_darwin_amd64.tar.gz"
      sha256 "40e9a4d095ae75cf76d37373b179852c0d2927ce8b3c91c550e3389c3ce68d02"

      define_method(:install) do
        bin.install "stratt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stratt-sh/stratt/releases/download/v0.13.0/stratt_0.13.0_darwin_arm64.tar.gz"
      sha256 "f96bb648621cc49a1a878adc538fe58bedd10e05f944959517a398a7102dddb0"

      define_method(:install) do
        bin.install "stratt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stratt-sh/stratt/releases/download/v0.13.0/stratt_0.13.0_linux_amd64.tar.gz"
      sha256 "cc66c64c461da6efd9cc5ee8d746ce3ff0a774f655e3a92887bd0fab81119260"
      define_method(:install) do
        bin.install "stratt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stratt-sh/stratt/releases/download/v0.13.0/stratt_0.13.0_linux_arm64.tar.gz"
      sha256 "2bfccfb2d90901a006850698fd59c81ffa15329cb4621b761811432bfd974255"
      define_method(:install) do
        bin.install "stratt"
      end
    end
  end

  test do
    system "#{bin}/stratt version"
  end
end
