# This file was generated by GoReleaser. DO NOT EDIT.
cask "stratt" do
  version "0.19.0"

  on_macos do
    on_intel do
      sha256 "d8d97f5de29a48a5f641824329ba11274dce41e707e2c3f86c2ff43148128ea4"
      url "https://github.com/stratt-sh/stratt/releases/download/v#{version}/stratt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "569aa21c1f20b1bd194911ab0becf1e4861cb16c8a6c51000e17d8ae7051835b"
      url "https://github.com/stratt-sh/stratt/releases/download/v#{version}/stratt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "006a6ab676932764b88c2edee528a301a6cec57b81d1a115c9473d137de41fc0"
      url "https://github.com/stratt-sh/stratt/releases/download/v#{version}/stratt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "34dd053938675aa91d8d6628f9d8ee61960b9b020341de27ff952d6ddcca5d05"
      url "https://github.com/stratt-sh/stratt/releases/download/v#{version}/stratt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stratt"
  desc "One set of commands for every repo, whatever language it's in — build, test, lint, release, deploy."
  homepage "https://stratt.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stratt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stratt"]
    end
  end

  # No zap stanza required

end
