# This file was generated by GoReleaser. DO NOT EDIT.
cask "stratt" do
  version "0.20.0"

  on_macos do
    on_intel do
      sha256 "9b59b39ce971b328c3b72369993aa7d19fc7e8f45d841fdc915a91f2b6e36fba"
      url "https://github.com/stratt-sh/stratt/releases/download/v#{version}/stratt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7cfb99ac20763e266f3ad14f55dec37c0675ea9f8cc92d702666aded6cc5575b"
      url "https://github.com/stratt-sh/stratt/releases/download/v#{version}/stratt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ba2973b37e21768c594b7e7cfa53b47ed24aa400b7c581494bef8354cab20574"
      url "https://github.com/stratt-sh/stratt/releases/download/v#{version}/stratt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8724221d5ab32f88cdc1b422cd4a9d396b65c730f96d7636c4dcde9ccdde0c1d"
      url "https://github.com/stratt-sh/stratt/releases/download/v#{version}/stratt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stratt"
  desc "One set of commands for every repo, whatever language it's in — build, test, lint, release, deploy."
  homepage "https://stratt.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stratt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stratt"]
    end
  end

  # No zap stanza required

end
