# This file was generated by GoReleaser. DO NOT EDIT.
cask "stratt" do
  version "0.17.0"

  on_macos do
    on_intel do
      sha256 "214bca202767fcd05bc6611d3c0ca493b5fba63469d52b49a752d1bb15d691ec"
      url "https://github.com/stratt-sh/stratt/releases/download/v#{version}/stratt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "14185e0aa8534206e54a25a72ca48c8a1c3bbced50d7e2e9d3cebf9bbe045531"
      url "https://github.com/stratt-sh/stratt/releases/download/v#{version}/stratt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "adcef05281d04769a889422adeaf99f6dea0a0401da343bae990e4cd13b547dd"
      url "https://github.com/stratt-sh/stratt/releases/download/v#{version}/stratt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5e34f4383c6fcdbcb7e3d7abf0671d6b355df6d27772fd1a84ec332d48e7b5ae"
      url "https://github.com/stratt-sh/stratt/releases/download/v#{version}/stratt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stratt"
  desc "One set of commands for every repo, whatever language it's in — build, test, lint, release, deploy."
  homepage "https://stratt.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stratt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stratt"]
    end
  end

  # No zap stanza required

end
